### ISSUE TITLE
Create index page so both son of sam and NYC history are linked

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/that-was-then#1]
It will live at http://interactive.nydailynews.com/project/archive/ and should have the standard header / footer of the site, and look like http://interactive.nydailynews.com/project/ .

It should be managed by a data.csv that's stored in https://github.com/nydailynews/data-dot-csv

**Comment by kelliparker** [comment]
I think this is done but take a look, please.

**Comment by freejoe76** [comment]
Looks great http://interactive.nydailynews.com/project/archive/
